Added the ability to use wildcards in the input file/dir parameters.

diff --git a/subedit b/subedit
--- a/subedit
+++ b/subedit
@@ -206,7 +206,7 @@ examplecounter=1
 
 text2="${cyan}NOTES${normal}
   • If the argument is a subtitle file you can give a relative or absolute path or a filename in the working directory.
-  • Filenames must be enclosed in quotes if they contain spaces or other special characters.
+  • Filenames must be enclosed in quotes if they contain spaces or other special characters (including wildcards).
   • Do not use \"~\" or \"\$HOME\" to symbolize the home directory. Write the text instead (/home/yourname).
   • -i (input file) or -d (input directory) is required in every case.
   • If only -i parameter is used then the subtitle goes through a basic clean-up (empty subtitles are removed etc.)
@@ -224,9 +224,14 @@ text2+="${cyan}EXAMPLES${normal}
   subedit -i foo.srt
   Removes empty subtitles, duplicate subtitles and extra empty lines, fixes subtitles' indexes, etc.\n\n"
 
+
+text2+="  ${bold}${green}Example $((examplecounter++))${normal}
+  subedit -i \"*.srt\"
+  Same as above, but applies to all .srt files.\n\n"
+
 text2+="  ${bold}${green}Example $((examplecounter++))${normal}
   subedit -i foo.srt -b
-  Same as above, but creates a backup before processing the subtitle.\n\n"
+  Same as Example $exmpl, but creates a backup before processing the subtitle.\n\n"
 
 text2+="  ${bold}${green}Example $((examplecounter++))${normal}
   subedit -d foo_directory
@@ -234,7 +239,16 @@ text2+="  ${bold}${green}Example $((examplecounter++))${normal}
 
 text2+="  ${bold}${green}Example $((examplecounter++))${normal}
   subedit -d foo_directory -r
-  Same as above, but also processes subtitles found in subdirectories (unlimited depth) as well.\n\n\n"
+  Same as above, but also processes subtitles found in subdirectories (unlimited depth) as well.\n\n"
+
+text2+="  ${bold}${green}Example $((examplecounter++))${normal}
+  subedit -d \"Season*\" -b
+  Runs Basic clean-up for all subtitles found in all folders that begin with \"Season\" and
+  creates a backup for each subtitle.\n\n"
+
+text2+="  ${bold}${green}Example $((examplecounter++))${normal}
+  subedit -d \"Season [1-3,5]\"
+  Runs Basic clean-up for all subtitles found in the folders \"Season 1\", \"Season 2\", \"Season 3\" and \"Season 5\".\n\n\n"
 
 
 text2+="  ${bold}Shift time${normal}
@@ -260,6 +274,10 @@ text2+="  ${bold}${green}Example $((examplecounter++))${normal}
   Calculates and applies the appropriate shift time value so that the last subtitle starts at 01:38:32,600.\n\n"
 
 text2+="  ${bold}${green}Example $((examplecounter++))${normal}
+  subedit -i \"*.srt\" -s 00:00:02,000
+  Shifts time by 2.0 seconds in all .srt subtitle files.\n\n"
+
+text2+="  ${bold}${green}Example $((examplecounter++))${normal}
   subedit -d foo_directory -s 00:00:01,700
   Shifts time by 1.7 seconds in all .srt subtitle files in directory \"foo_directory\".\n\n\n"
 
@@ -267,7 +285,11 @@ text2+="  ${bold}${green}Example $((examplecounter++))${normal}
 text2+="  ${bold}Convert NTSC to PAL${normal}
 
   ${bold}${green}Example $((examplecounter++))${normal}
-  subedit -i foo.srt -p\n\n\n"
+  subedit -i foo.srt -p\n\n"
+
+text2+="  ${bold}${green}Example $((examplecounter++))${normal}
+  subedit -i \"*.srt\" -p
+  Converts the fps in all .srt subtitle files.\n\n\n"
 
 
 text2+="  ${bold}Convert PAL to NTSC${normal}
@@ -381,6 +403,10 @@ text2+="  ${bold}${green}Example $((examplecounter++))${normal}
   Assumes that foo.sub is in 15.338 fps and creates a new file foo.srt.\n\n"
 
 text2+="  ${bold}${green}Example $((examplecounter++))${normal}
+  subedit -i \"*.sub\" -t film
+  Assumes that all .sub subtitle files are in 23.976 fps and converts them to srt.\n\n"
+
+text2+="  ${bold}${green}Example $((examplecounter++))${normal}
   subedit -d foo_directory -t film
   Assumes that all .sub subtitle files in \"foo_directory\" are in 23.976 fps and converts them to srt.\n\n\n"
 
@@ -479,6 +505,11 @@ text2+="  ${bold}Clean trash${normal}
   ${bold}${green}Example $((examplecounter++))${normal}
   subedit -i foo.srt -c
   Cleans foo.srt.\n\n"
+
+text2+="  ${bold}${green}Example $((examplecounter++))${normal}
+  subedit -i \"*\" -c -b
+  Cleans all subtitle files and creates a backup for each one before processing them.
+  Files that are not subtitle files are not processed.\n\n"
 
 text2+="  ${bold}${green}Example $((examplecounter++))${normal}
   subedit -d foo_directory -c -b
@@ -583,18 +614,18 @@ check_file ()
 {
 	if ! [[ -f "$1" ]]; then
 		echo "Error: \"$1\" not found."
-		[[ "$inputdirectory" ]] && return 1 || exit 1
+		return 1
 	fi
 
 	if ! [[ -r "$1" ]]; then
 		echo "Error: \"$1\" is not readable."
-		[[ "$inputdirectory" ]] && return 1 || exit 1
+		return 1
 	fi
 
 	encoding=$(file -b --mime-encoding "$1")
 	if [[ $encoding == "binary" ]] || ! [[ $(file -b "$1") == *"text"* ]] && ! [[ $(file -b "$1") == *"Bio-Rad .PIC Image File"* ]]; then
 		echo "Error: \"$1\" is not a text file or it is UTF-16 without BOM"
-		[[ "$inputdirectory" ]] && return 1 || exit 1
+		return 1
 	fi
 
 	# Check the file extension and create backup if it's not srt or sub
@@ -962,7 +993,7 @@ check_srt ()
 			mv "$1.bak" "$1" 2> /dev/null
 		fi
 		echo "Error: \"$1\" is not a valid srt file"
-		[[ "$inputdirectory" ]] && return 1 || exit 1
+		return 1
 	elif ! [[ $backup ]]; then
 		rm -f "$1.bak" 2> /dev/null
 	fi
@@ -998,7 +1029,7 @@ check_sub ()
 			mv "$1.bak" "$1" 2> /dev/null
 		fi
 		echo "Error: \"$1\" is not a valid sub file"
-		[[ "$inputdirectory" ]] && return 1 || exit 1
+		return 1
 	elif ! [[ $backup ]]; then
 		rm -f "$1.bak" 2> /dev/null
 	fi
@@ -1050,7 +1081,7 @@ check_srt_and_sub ()
 	if ! [[ $subtitleis ]]; then
 		mv "$1.bak" "$1" 2> /dev/null
 		echo "Error: \"$1\" is not a valid srt or sub file"
-		[[ "$inputdirectory" ]] && return 1 || exit 1
+		return 1
 	elif ! [[ $backup ]]; then
 		rm -f "$1.bak" 2> /dev/null
 	fi
@@ -4260,69 +4291,76 @@ delete_HI ()
 }
 
 
-if [[ $inputfilename ]]; then
-	if [[ $shifttime ]]; then
-		shift_time; (($? != 0)) && exit 1
-	fi
+# Check for incompatible parameters
+if [[ $inputfilename ]] && [[ $inputdirectory ]]; then
+	echo "Error: The parameters -i (Input file) and -d (Input directory) cannot be used together."; exit 1
+fi
 
-	if [[ $pal2ntsc ]] || [[ $ntsc2pal ]]; then
-		change_fps; (($? != 0)) && exit 1
-	fi
-
-	if [[ $adjustfirst ]]; then
-		adjust_time; (($? != 0)) && exit 1
-	fi
-
-	if [[ $adjustonlyfirst ]] || [[ $adjustonlylast ]]; then
-		adjust_time_v2; (($? != 0)) && exit 1
-	fi
-
-	if [[ $synchronizefile ]]; then
-		synchronize_with_file; (($? != 0)) && exit 1
-	fi
-
-	if [[ $findci ]] || [[ $findcs ]]; then
-		find_text; (($? != 0)) && exit 1
-	fi
-
-	if [[ $replace1 ]] || [[ $replace3 ]]; then
-		replace_text; (($? != 0)) && exit 1
-	fi
-
-	if [[ $sub2srt ]]; then
-		sub2_srt; (($? != 0)) && exit 1
-	elif [[ $srt2sub ]]; then
-		srt2_sub; (($? != 0)) && exit 1
-	fi
-
-	if [[ $joinsrt ]]; then
-		join_srt; (($? != 0)) && exit 1
-	fi
-
-	if [[ $splitsrt ]]; then
-		split_srt; (($? != 0)) && exit 1
-	fi
-
-	if [[ $cleantrash ]]; then
-		clean_trash; (($? != 0)) && exit 1
-	fi
-
-	if [[ $deletetextsforHI ]]; then
-		delete_HI; (($? != 0)) && exit 1
-	fi
-
-	if ! [[ $srtok ]] && ! [[ $subok ]] && ! [[ $subtitleis ]]; then
-		basic_clean_up; (($? != 0)) && exit 1
-	fi
-	exit 0
+if [[ $inputfilename ]] && [[ $synchronizedirectory ]]; then
+	echo "Error: The parameters -i (Input file) and -D (Synchronize with directory.) cannot be used together."
+	echo "Instead of \"Synchronize with directory\" you can use \"Synchronize with file\" (-y parameter)."; exit 1
 fi
 
 
-if [[ $inputdirectory ]]; then
-	if ! [[ -e $inputdirectory ]]; then
-		echo "Error: \"$inputdirectory\" not found."; exit 1
+# Input file with wildcard support
+master_function ()
+{
+	if [[ $shifttime ]]; then
+		shift_time; (($? != 0)) && return 1
 	fi
 
+	if [[ $pal2ntsc ]] || [[ $ntsc2pal ]]; then
+		change_fps; (($? != 0)) && return 1
+	fi
+
+	if [[ $adjustfirst ]]; then
+		adjust_time; (($? != 0)) && return 1
+	fi
+
+	if [[ $adjustonlyfirst ]] || [[ $adjustonlylast ]]; then
+		adjust_time_v2; (($? != 0)) && return 1
+	fi
+
+	if [[ $synchronizefile ]]; then
+		synchronize_with_file; (($? != 0)) && return 1
+	fi
+
+	if [[ $findci ]] || [[ $findcs ]]; then
+		find_text; (($? != 0)) && return 1
+	fi
+
+	if [[ $replace1 ]] || [[ $replace3 ]]; then
+		replace_text; (($? != 0)) && return 1
+	fi
+
+	if [[ $sub2srt ]]; then
+		sub2_srt; (($? != 0)) && return 1
+	elif [[ $srt2sub ]]; then
+		srt2_sub; (($? != 0)) && return 1
+	fi
+
+	if [[ $joinsrt ]]; then
+		join_srt; (($? != 0)) && return 1
+	fi
+
+	if [[ $splitsrt ]]; then
+		split_srt; (($? != 0)) && return 1
+	fi
+
+	if [[ $cleantrash ]]; then
+		clean_trash; (($? != 0)) && return 1
+	fi
+
+	if [[ $deletetextsforHI ]]; then
+		delete_HI; (($? != 0)) && return 1
+	fi
+
+	if ! [[ $srtok ]] && ! [[ $subok ]] && ! [[ $subtitleis ]]; then
+		basic_clean_up; (($? != 0)) && return 1
+	fi
+}
+
+if [[ $inputfilename ]]; then
 	# Set globbing to case insensitive
 	shopt -s nocaseglob
 
@@ -4330,30 +4368,94 @@ if [[ $inputdirectory ]]; then
 	IFS=$'\n'			# new field separator, the end of line
 
 	# Capture the output of ls to an array
+	filesarray=( $(ls $inputfilename -p -d 2> /dev/null | grep -v /) )
+
+	IFS=$old_IFS		# restore default field separator
+
+	# Restore globbing to case sensitive
+	shopt -u nocaseglob
+
+	if ((${#filesarray[@]} == 0)); then
+		echo "Error: No file found."; exit 1
+	elif ((${#filesarray[@]} == 1)); then
+		master_function
+
+		# Exit if the return code of anything in the master_function is not 0
+		if (($? != 0)); then
+			exit 1
+		else
+			exit 0
+		fi
+	else
+		numberofsrt=$(printf "%s\n" "${filesarray[@]}" | grep -i "\.srt$" -c)
+		numberofsub=$(printf "%s\n" "${filesarray[@]}" | grep -i "\.sub$" -c)
+		echo "$numberofsrt .srt & $numberofsub .sub file(s) found"
+		((numberofother = ${#filesarray[@]} - $numberofsrt - $numberofsub))
+		if ((numberofother > 0)); then
+			echo "$numberofother other file(s) were also found. These will be checked too and processed if they are subtitles."
+		fi
+
+		batchcounter=0
+		numberofsubtitles=${#filesarray[@]}
+		numberofsubtitleslength=${#numberofsubtitles}
+		for inputfilename in "${filesarray[@]}"; do
+			((batchcounter++))
+			batchcounterlength=${#batchcounter}
+			spaceslength=$((numberofsubtitleslength-batchcounterlength))
+			case "$spaceslength" in
+				0) precedingspaces="" ;;
+				1) precedingspaces=" " ;;
+				2) precedingspaces="  " ;;
+				3) precedingspaces="   " ;;
+				?) precedingspaces=$(eval printf "\ %.0s" {1..$spaceslength}) ;;
+			esac
+			printf "${bold}${green}[$precedingspaces$batchcounter/${#filesarray[@]}]${normal} "
+
+			master_function
+		done
+		exit 0
+	fi
+fi
+
+
+# Input directory with wildcard support
+if [[ $inputdirectory ]]; then
+	# Set globbing to case insensitive
+	shopt -s nocaseglob
+
+	old_IFS=$IFS		# save the field separator
+	IFS=$'\n'			# new field separator, the end of line
+
+	# Check if directory/ies exist
+	if ! [[ $(ls -p -d $inputdirectory 2> /dev/null | grep /) ]]; then
+		echo "Error: No directory found."; exit 1
+	fi
+
+	# Capture the output of ls to an array
 	if [[ $shifttime ]] || [[ $pal2ntsc ]] || [[ $ntsc2pal ]] || [[ $adjustfirst ]] || [[ $adjustonlyfirst ]] || [[ $adjustonlylast ]] || [[ $synchronizedirectory ]] || [[ $srt2sub ]] || [[ $splitsrt ]]; then
 		if [[ $recurse ]]; then
-			filesarray=( $(find "$inputdirectory" -type f -iname "*.srt" 2> /dev/null | sort) )
+			filesarray=( $(find $inputdirectory -type f -iname "*.srt" 2> /dev/null | sort) )
 		else
-			filesarray=( $(ls "$inputdirectory"/*.srt 2> /dev/null) )
+			filesarray=( $(ls $inputdirectory/*.srt 2> /dev/null) )
 		fi
-		echo "${#filesarray[@]} srt files found"
+		echo "${#filesarray[@]} srt file(s) found"
 	elif [[ $sub2srt ]]; then
 		if [[ $recurse ]]; then
-			filesarray=( $(find "$inputdirectory" -type f -iname "*.sub" 2> /dev/null | sort) )
+			filesarray=( $(find $inputdirectory -type f -iname "*.sub" 2> /dev/null | sort) )
 		else
-			filesarray=( $(ls "$inputdirectory"/*.sub 2> /dev/null) )
+			filesarray=( $(ls $inputdirectory/*.sub 2> /dev/null) )
 		fi
-		echo "${#filesarray[@]} sub files found"
+		echo "${#filesarray[@]} sub file(s) found"
 	elif [[ $synchronizefile ]] || [[ $joinsrt ]]; then
 		echo "Error: Synchronize with file and Join srt cannot be used in batch mode."
 		echo "Instead of Synchronize with file you can use Synchronize with directory (-D parameter)."; exit 1
 	else
 		if [[ $recurse ]]; then
-			filesarray=( $(find "$inputdirectory" -type f -iname "*.srt" -o -iname "*.sub" 2> /dev/null | sort) )
+			filesarray=( $(find $inputdirectory -type f -iname "*.srt" -o -iname "*.sub" 2> /dev/null | sort) )
 		else
-			filesarray=( $(ls "$inputdirectory"/*.srt "$inputdirectory"/*.sub 2> /dev/null) )
+			filesarray=( $(ls $inputdirectory/*.srt $inputdirectory/*.sub 2> /dev/null) )
 		fi
-		echo "$(printf "%s\n" "${filesarray[@]}" | grep -i "\.srt$" -c) srt & $(printf "%s\n" "${filesarray[@]}" | grep -i "\.sub$" -c) sub files found"
+		echo "$(printf "%s\n" "${filesarray[@]}" | grep -i "\.srt$" -c) .srt & $(printf "%s\n" "${filesarray[@]}" | grep -i "\.sub$" -c) .sub file(s) found"
 	fi
 
 	IFS=$old_IFS		# restore default field separator
